import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import { Nav } from "@/components/navbar";
import Footer from "@/components/landing/footer";
import GlobalBackground from '@/components/GlobalBackground';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark antialiased">
        <GlobalBackground />
        <NextTopLoader showSpinner={false} height={6} color="#000000" />
        <main className="h-screen">
          <Nav />
          <Toaster richColors position="top-right" />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
